### ISSUE TITLE
Broken resizable modern on init

### ISSUE THREAD

**Issue by ineedbots** [Villavu/SRL-Development#40]
![image](https://user-images.githubusercontent.com/751729/172247457-8c23e6b7-6aa4-4995-b5a2-6ea9cf4780ef.png)

Resizable classic is fine, only modern is problematic.

Was introduced with https://github.com/Villavu/SRL-Development/commit/f65bc17a9d9cfb93a5b76ffa3ff072c44e92c3cf#diff-c13d6128a5b1b778e39d958bf96f2f3bb436509d5e6ac9d647c043de73218e51R59

**Comment by ollydev** [comment]
Now fixed. Interfaces bounds should not be queried `SetupAlignment`. Preferably a offset should be assigned and then a function to return the bounds like how it's done in minimap.
