### ISSUE TITLE
False negative for Bank.IsOpen due to uptext

### ISSUE THREAD

**Issue by ineedbots** [Villavu/SRL-Development#41]
Often, the uptext will cover a part of one of the bank buttons, making Bank.IsOpen return false.

Possible solution: https://github.com/ineedbots/srl-osr-scripts/blob/master/utils.simba#L1219
Use some fixed text on the interface to trigger if its open, however, this doesn't work perfectly, as Bank.Height might break due to the uptext.

**Comment by Torwent** [comment]
I'm also not a fan of using button count to figure this out.
I've also faced occasional issues with it and some people disable/enable certain buttons.

I think the bank interface bounds are unique and maybe we could use the close button only to detect the bank open

**Comment by slackydev** [comment]
How can this be? I'd like some images.
![image](https://user-images.githubusercontent.com/1329664/173618768-5c675446-297e-46b1-a343-09145d296f4c.png)
The uptext covering the button marked in red looks impossible, is not this the button we use? I did not write it, but when I opened RS that worn button stood out to me as a perfect thing to search for, only to find that is in fact what we search for.

**Comment by ineedbots** [comment]
Not in my case 
![image](https://user-images.githubusercontent.com/751729/173664006-7ab9ce77-2223-4545-bc28-e4a942c2a4e6.png)

What are you bank settings?

**Comment by slackydev** [comment]
I am on 100% default setup. Cant find any special settings for this either.

**Comment by ineedbots** [comment]
RuneLite bank tags plugin related, disable the plugin or use vanilla client.
