### ISSUE TITLE
PlayerPoint becomes stale when OnWalkEvent is called for RSWalker

### ISSUE THREAD

**Issue by ineedbots** [Villavu/SRL-Development#53]
When OnWalkEvent could change the player's position, (for example, interacting with an object, like a door) PlayerPoint becomes stale in TRSWalker.WalkFinalStep and in TRSWalker.WalkStep.

![image](https://user-images.githubusercontent.com/751729/178429484-79283dd3-eb82-4b82-8544-e7045cc9cc9e.png)

Allow the PlayerPoint to modified from the event functions, or just update PlayerPoint after the event is called.

**Comment by slackydev** [comment]
So pass PlayerPoint as a reference to OnWalkEvents. This can be done for 1.5, since it's breaking.

**Comment by Torwent** [comment]
I was thinking.... if my TRSWalker backport does end up being accepted, we can and should do this

**Comment by ineedbots** [comment]
we are making breaking changes to 1400 srl?
